version: "3"
services:
  nginx-build:
    build:
      image: cus-nginx
      context: .
      dockerfile: dockerfile
  nginx-host:
    image: cus-nginx
    container_name: cus-nginx
      ports:
        - 80:80
